[package]
name = "sorting-visualizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-recursion = "1.0.2"
getrandom = { version = "0.2.8", features = ["js"] }
gloo-timers = { version = "0.2.6", features = ["futures"] }
leptos = "0.1.3"
rand = "0.8.5"
